//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: endcoin
// ----------------------------------------------------------------------------
pub mod endcoin {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for endcoin
    pub fn program_id() -> Pubkey {
        pubkey!("g9pxtrXmWHss8KWNtakwyMpPbnGnD1TCogYv9NDUcB8")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: ClaimReward
    // ....................................................................

    /// Main instruction struct for ClaimReward
    pub struct ClaimRewardInstruction {
        pub accounts: ClaimRewardInstructionAccountMetas,
        pub data: ClaimRewardInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ClaimReward instruction
    #[derive(Debug, Clone, Default)]
    pub struct ClaimRewardInstructionAccountMetas {
        pub pool: AccountMeta,

        pub claimer: AccountMeta,

        pub to_mint_a_account: AccountMeta,

        pub to_mint_b_account: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub reward_vault: AccountMeta,

        pub reward_account_a: AccountMeta,

        pub reward_account_b: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ClaimReward instruction
    #[derive(Debug, Clone)]
    pub struct ClaimRewardInstructionAccounts {
        pub pool: Pubkey,

        pub claimer: Pubkey,

        pub to_mint_a_account: Pubkey,

        pub to_mint_b_account: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub reward_vault: Pubkey,

        pub reward_account_a: Pubkey,

        pub reward_account_b: Pubkey,
    }

    impl ClaimRewardInstructionAccounts {
        pub fn new(
            pool: Pubkey,

            claimer: Pubkey,

            to_mint_a_account: Pubkey,

            to_mint_b_account: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            reward_vault: Pubkey,

            reward_account_a: Pubkey,

            reward_account_b: Pubkey,
        ) -> Self {
            Self {
                pool,

                claimer,

                to_mint_a_account,

                to_mint_b_account,

                mint_a,

                mint_b,

                reward_vault,

                reward_account_a,

                reward_account_b,
            }
        }
    }

    /// Instruction data for ClaimReward
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ClaimRewardInstructionData {
        pub claimer: Pubkey,

        pub amount_a: u64,

        pub amount_b: u64,
    }

    impl ClaimRewardInstructionData {
        pub fn new(claimer: Pubkey, amount_a: u64, amount_b: u64) -> Self {
            Self {
                claimer,

                amount_a,

                amount_b,
            }
        }
    }

    /// Implementation for ClaimRewardInstruction
    impl ClaimRewardInstruction {
        fn discriminator() -> [u8; 8] {
            [149u8, 95u8, 181u8, 242u8, 94u8, 90u8, 158u8, 162u8]
        }

        pub fn data(data: ClaimRewardInstructionData) -> Self {
            Self {
                accounts: ClaimRewardInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ClaimRewardInstructionAccounts) -> Self {
            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.claimer = AccountMeta::new(accounts.claimer, true);

            self.accounts.to_mint_a_account = AccountMeta::new(accounts.to_mint_a_account, false);

            self.accounts.to_mint_b_account = AccountMeta::new(accounts.to_mint_b_account, false);

            self.accounts.mint_a = AccountMeta::new(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new(accounts.mint_b, false);

            self.accounts.reward_vault = AccountMeta::new_readonly(accounts.reward_vault, false);

            self.accounts.reward_account_a = AccountMeta::new(accounts.reward_account_a, false);

            self.accounts.reward_account_b = AccountMeta::new(accounts.reward_account_b, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.claimer.clone());

            metas.push(self.accounts.to_mint_a_account.clone());

            metas.push(self.accounts.to_mint_b_account.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.reward_account_a.clone());

            metas.push(self.accounts.reward_account_b.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateAmm
    // ....................................................................

    /// Main instruction struct for CreateAmm
    pub struct CreateAmmInstruction {
        pub accounts: CreateAmmInstructionAccountMetas,
        pub data: CreateAmmInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateAmm instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateAmmInstructionAccountMetas {
        pub amm: AccountMeta,

        pub admin: AccountMeta,

        pub authority: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateAmm instruction
    #[derive(Debug, Clone)]
    pub struct CreateAmmInstructionAccounts {
        pub amm: Pubkey,

        pub admin: Pubkey,

        pub authority: Pubkey,
    }

    impl CreateAmmInstructionAccounts {
        pub fn new(amm: Pubkey, admin: Pubkey, authority: Pubkey) -> Self {
            Self {
                amm,

                admin,

                authority,
            }
        }
    }

    /// Instruction data for CreateAmm
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateAmmInstructionData {
        pub fee: u16,
    }

    impl CreateAmmInstructionData {
        pub fn new(fee: u16) -> Self {
            Self { fee }
        }
    }

    /// Implementation for CreateAmmInstruction
    impl CreateAmmInstruction {
        fn discriminator() -> [u8; 8] {
            [242u8, 91u8, 21u8, 170u8, 5u8, 68u8, 125u8, 64u8]
        }

        pub fn data(data: CreateAmmInstructionData) -> Self {
            Self {
                accounts: CreateAmmInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateAmmInstructionAccounts) -> Self {
            self.accounts.amm = AccountMeta::new(accounts.amm, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreatePool
    // ....................................................................

    /// Main instruction struct for CreatePool
    pub struct CreatePoolInstruction {
        pub accounts: CreatePoolInstructionAccountMetas,
        pub data: CreatePoolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreatePool instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreatePoolInstructionAccountMetas {
        pub amm: AccountMeta,

        pub pool: AccountMeta,

        pub pool_authority: AccountMeta,

        pub mint_liquidity: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CreatePool instruction
    #[derive(Debug, Clone)]
    pub struct CreatePoolInstructionAccounts {
        pub amm: Pubkey,

        pub pool: Pubkey,

        pub pool_authority: Pubkey,

        pub mint_liquidity: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub payer: Pubkey,
    }

    impl CreatePoolInstructionAccounts {
        pub fn new(
            amm: Pubkey,

            pool: Pubkey,

            pool_authority: Pubkey,

            mint_liquidity: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                amm,

                pool,

                pool_authority,

                mint_liquidity,

                mint_a,

                mint_b,

                payer,
            }
        }
    }

    /// Instruction data for CreatePool
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreatePoolInstructionData {}

    impl CreatePoolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreatePoolInstruction
    impl CreatePoolInstruction {
        fn discriminator() -> [u8; 8] {
            [233u8, 146u8, 209u8, 142u8, 207u8, 104u8, 64u8, 188u8]
        }

        pub fn data(data: CreatePoolInstructionData) -> Self {
            Self {
                accounts: CreatePoolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreatePoolInstructionAccounts) -> Self {
            self.accounts.amm = AccountMeta::new_readonly(accounts.amm, false);

            self.accounts.pool = AccountMeta::new(accounts.pool, false);

            self.accounts.pool_authority =
                AccountMeta::new_readonly(accounts.pool_authority, false);

            self.accounts.mint_liquidity =
                AccountMeta::new_readonly(accounts.mint_liquidity, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.pool_authority.clone());

            metas.push(self.accounts.mint_liquidity.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateRewardTokenAccounts
    // ....................................................................

    /// Main instruction struct for CreateRewardTokenAccounts
    pub struct CreateRewardTokenAccountsInstruction {
        pub accounts: CreateRewardTokenAccountsInstructionAccountMetas,
        pub data: CreateRewardTokenAccountsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateRewardTokenAccounts instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateRewardTokenAccountsInstructionAccountMetas {
        pub pool: AccountMeta,

        pub amm: AccountMeta,

        pub reward_account_a: AccountMeta,

        pub reward_account_b: AccountMeta,

        pub reward_vault: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CreateRewardTokenAccounts instruction
    #[derive(Debug, Clone)]
    pub struct CreateRewardTokenAccountsInstructionAccounts {
        pub pool: Pubkey,

        pub amm: Pubkey,

        pub reward_account_a: Pubkey,

        pub reward_account_b: Pubkey,

        pub reward_vault: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub payer: Pubkey,
    }

    impl CreateRewardTokenAccountsInstructionAccounts {
        pub fn new(
            pool: Pubkey,

            amm: Pubkey,

            reward_account_a: Pubkey,

            reward_account_b: Pubkey,

            reward_vault: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                pool,

                amm,

                reward_account_a,

                reward_account_b,

                reward_vault,

                mint_a,

                mint_b,

                payer,
            }
        }
    }

    /// Instruction data for CreateRewardTokenAccounts
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateRewardTokenAccountsInstructionData {}

    impl CreateRewardTokenAccountsInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateRewardTokenAccountsInstruction
    impl CreateRewardTokenAccountsInstruction {
        fn discriminator() -> [u8; 8] {
            [167u8, 52u8, 19u8, 26u8, 10u8, 6u8, 135u8, 23u8]
        }

        pub fn data(data: CreateRewardTokenAccountsInstructionData) -> Self {
            Self {
                accounts: CreateRewardTokenAccountsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateRewardTokenAccountsInstructionAccounts) -> Self {
            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.amm = AccountMeta::new_readonly(accounts.amm, false);

            self.accounts.reward_account_a = AccountMeta::new(accounts.reward_account_a, false);

            self.accounts.reward_account_b = AccountMeta::new(accounts.reward_account_b, false);

            self.accounts.reward_vault = AccountMeta::new_readonly(accounts.reward_vault, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.reward_account_a.clone());

            metas.push(self.accounts.reward_account_b.clone());

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateRewardVault
    // ....................................................................

    /// Main instruction struct for CreateRewardVault
    pub struct CreateRewardVaultInstruction {
        pub accounts: CreateRewardVaultInstructionAccountMetas,
        pub data: CreateRewardVaultInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateRewardVault instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateRewardVaultInstructionAccountMetas {
        pub reward_vault: AccountMeta,

        pub pool: AccountMeta,

        pub amm: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CreateRewardVault instruction
    #[derive(Debug, Clone)]
    pub struct CreateRewardVaultInstructionAccounts {
        pub reward_vault: Pubkey,

        pub pool: Pubkey,

        pub amm: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub payer: Pubkey,
    }

    impl CreateRewardVaultInstructionAccounts {
        pub fn new(
            reward_vault: Pubkey,

            pool: Pubkey,

            amm: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                reward_vault,

                pool,

                amm,

                mint_a,

                mint_b,

                payer,
            }
        }
    }

    /// Instruction data for CreateRewardVault
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateRewardVaultInstructionData {}

    impl CreateRewardVaultInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateRewardVaultInstruction
    impl CreateRewardVaultInstruction {
        fn discriminator() -> [u8; 8] {
            [56u8, 81u8, 16u8, 1u8, 27u8, 121u8, 171u8, 249u8]
        }

        pub fn data(data: CreateRewardVaultInstructionData) -> Self {
            Self {
                accounts: CreateRewardVaultInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateRewardVaultInstructionAccounts) -> Self {
            self.accounts.reward_vault = AccountMeta::new(accounts.reward_vault, false);

            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.amm = AccountMeta::new_readonly(accounts.amm, false);

            self.accounts.mint_a = AccountMeta::new(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new(accounts.mint_b, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateSst
    // ....................................................................

    /// Main instruction struct for CreateSst
    pub struct CreateSstInstruction {
        pub accounts: CreateSstInstructionAccountMetas,
        pub data: CreateSstInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateSst instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateSstInstructionAccountMetas {
        pub sst: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CreateSst instruction
    #[derive(Debug, Clone)]
    pub struct CreateSstInstructionAccounts {
        pub sst: Pubkey,

        pub payer: Pubkey,
    }

    impl CreateSstInstructionAccounts {
        pub fn new(sst: Pubkey, payer: Pubkey) -> Self {
            Self { sst, payer }
        }
    }

    /// Instruction data for CreateSst
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateSstInstructionData {}

    impl CreateSstInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateSstInstruction
    impl CreateSstInstruction {
        fn discriminator() -> [u8; 8] {
            [12u8, 63u8, 185u8, 8u8, 187u8, 143u8, 146u8, 65u8]
        }

        pub fn data(data: CreateSstInstructionData) -> Self {
            Self {
                accounts: CreateSstInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateSstInstructionAccounts) -> Self {
            self.accounts.sst = AccountMeta::new(accounts.sst, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.sst.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateTokenAccounts
    // ....................................................................

    /// Main instruction struct for CreateTokenAccounts
    pub struct CreateTokenAccountsInstruction {
        pub accounts: CreateTokenAccountsInstructionAccountMetas,
        pub data: CreateTokenAccountsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateTokenAccounts instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateTokenAccountsInstructionAccountMetas {
        pub pool_account_a: AccountMeta,

        pub pool_account_b: AccountMeta,

        pub pool_authority: AccountMeta,

        pub amm: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for CreateTokenAccounts instruction
    #[derive(Debug, Clone)]
    pub struct CreateTokenAccountsInstructionAccounts {
        pub pool_account_a: Pubkey,

        pub pool_account_b: Pubkey,

        pub pool_authority: Pubkey,

        pub amm: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub payer: Pubkey,
    }

    impl CreateTokenAccountsInstructionAccounts {
        pub fn new(
            pool_account_a: Pubkey,

            pool_account_b: Pubkey,

            pool_authority: Pubkey,

            amm: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                pool_account_a,

                pool_account_b,

                pool_authority,

                amm,

                mint_a,

                mint_b,

                payer,
            }
        }
    }

    /// Instruction data for CreateTokenAccounts
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateTokenAccountsInstructionData {}

    impl CreateTokenAccountsInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CreateTokenAccountsInstruction
    impl CreateTokenAccountsInstruction {
        fn discriminator() -> [u8; 8] {
            [163u8, 216u8, 49u8, 204u8, 97u8, 16u8, 80u8, 167u8]
        }

        pub fn data(data: CreateTokenAccountsInstructionData) -> Self {
            Self {
                accounts: CreateTokenAccountsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateTokenAccountsInstructionAccounts) -> Self {
            self.accounts.pool_account_a = AccountMeta::new(accounts.pool_account_a, false);

            self.accounts.pool_account_b = AccountMeta::new(accounts.pool_account_b, false);

            self.accounts.pool_authority =
                AccountMeta::new_readonly(accounts.pool_authority, false);

            self.accounts.amm = AccountMeta::new_readonly(accounts.amm, false);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool_account_a.clone());

            metas.push(self.accounts.pool_account_b.clone());

            metas.push(self.accounts.pool_authority.clone());

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositLiquidity
    // ....................................................................

    /// Main instruction struct for DepositLiquidity
    pub struct DepositLiquidityInstruction {
        pub accounts: DepositLiquidityInstructionAccountMetas,
        pub data: DepositLiquidityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositLiquidity instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositLiquidityInstructionAccountMetas {
        pub pool: AccountMeta,

        pub pool_authority: AccountMeta,

        pub payer: AccountMeta,

        pub mint_liquidity: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub pool_account_a: AccountMeta,

        pub pool_account_b: AccountMeta,

        pub depositor_account_liquidity: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub mint_authority: AccountMeta,
    }

    /// Account pubkeys for DepositLiquidity instruction
    #[derive(Debug, Clone)]
    pub struct DepositLiquidityInstructionAccounts {
        pub pool: Pubkey,

        pub pool_authority: Pubkey,

        pub payer: Pubkey,

        pub mint_liquidity: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub pool_account_a: Pubkey,

        pub pool_account_b: Pubkey,

        pub depositor_account_liquidity: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl DepositLiquidityInstructionAccounts {
        pub fn new(
            pool: Pubkey,

            pool_authority: Pubkey,

            payer: Pubkey,

            mint_liquidity: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            pool_account_a: Pubkey,

            pool_account_b: Pubkey,

            depositor_account_liquidity: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                pool,

                pool_authority,

                payer,

                mint_liquidity,

                mint_a,

                mint_b,

                pool_account_a,

                pool_account_b,

                depositor_account_liquidity,

                mint_authority,
            }
        }
    }

    /// Instruction data for DepositLiquidity
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositLiquidityInstructionData {
        pub mean_temp: f64,
    }

    impl DepositLiquidityInstructionData {
        pub fn new(mean_temp: f64) -> Self {
            Self { mean_temp }
        }
    }

    /// Implementation for DepositLiquidityInstruction
    impl DepositLiquidityInstruction {
        fn discriminator() -> [u8; 8] {
            [245u8, 99u8, 59u8, 25u8, 151u8, 71u8, 233u8, 249u8]
        }

        pub fn data(data: DepositLiquidityInstructionData) -> Self {
            Self {
                accounts: DepositLiquidityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositLiquidityInstructionAccounts) -> Self {
            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.pool_authority = AccountMeta::new(accounts.pool_authority, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.mint_liquidity = AccountMeta::new(accounts.mint_liquidity, false);

            self.accounts.mint_a = AccountMeta::new(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new(accounts.mint_b, false);

            self.accounts.pool_account_a = AccountMeta::new(accounts.pool_account_a, false);

            self.accounts.pool_account_b = AccountMeta::new(accounts.pool_account_b, false);

            self.accounts.depositor_account_liquidity =
                AccountMeta::new(accounts.depositor_account_liquidity, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.mint_authority = AccountMeta::new(accounts.mint_authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.pool_authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.mint_liquidity.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.pool_account_a.clone());

            metas.push(self.accounts.pool_account_b.clone());

            metas.push(self.accounts.depositor_account_liquidity.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: DepositRewards
    // ....................................................................

    /// Main instruction struct for DepositRewards
    pub struct DepositRewardsInstruction {
        pub accounts: DepositRewardsInstructionAccountMetas,
        pub data: DepositRewardsInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for DepositRewards instruction
    #[derive(Debug, Clone, Default)]
    pub struct DepositRewardsInstructionAccountMetas {
        pub reward_vault: AccountMeta,

        pub pool: AccountMeta,

        pub payer: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub reward_account_a: AccountMeta,

        pub reward_account_b: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,

        pub mint_authority: AccountMeta,
    }

    /// Account pubkeys for DepositRewards instruction
    #[derive(Debug, Clone)]
    pub struct DepositRewardsInstructionAccounts {
        pub reward_vault: Pubkey,

        pub pool: Pubkey,

        pub payer: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub reward_account_a: Pubkey,

        pub reward_account_b: Pubkey,

        pub mint_authority: Pubkey,
    }

    impl DepositRewardsInstructionAccounts {
        pub fn new(
            reward_vault: Pubkey,

            pool: Pubkey,

            payer: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            reward_account_a: Pubkey,

            reward_account_b: Pubkey,

            mint_authority: Pubkey,
        ) -> Self {
            Self {
                reward_vault,

                pool,

                payer,

                mint_a,

                mint_b,

                reward_account_a,

                reward_account_b,

                mint_authority,
            }
        }
    }

    /// Instruction data for DepositRewards
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct DepositRewardsInstructionData {
        pub mean_temp: f64,
    }

    impl DepositRewardsInstructionData {
        pub fn new(mean_temp: f64) -> Self {
            Self { mean_temp }
        }
    }

    /// Implementation for DepositRewardsInstruction
    impl DepositRewardsInstruction {
        fn discriminator() -> [u8; 8] {
            [52u8, 249u8, 112u8, 72u8, 206u8, 161u8, 196u8, 1u8]
        }

        pub fn data(data: DepositRewardsInstructionData) -> Self {
            Self {
                accounts: DepositRewardsInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: DepositRewardsInstructionAccounts) -> Self {
            self.accounts.reward_vault = AccountMeta::new_readonly(accounts.reward_vault, false);

            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.mint_a = AccountMeta::new(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new(accounts.mint_b, false);

            self.accounts.reward_account_a = AccountMeta::new(accounts.reward_account_a, false);

            self.accounts.reward_account_b = AccountMeta::new(accounts.reward_account_b, false);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.mint_authority = AccountMeta::new(accounts.mint_authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.reward_vault.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.reward_account_a.clone());

            metas.push(self.accounts.reward_account_b.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.mint_authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PullFeed
    // ....................................................................

    /// Main instruction struct for PullFeed
    pub struct PullFeedInstruction {
        pub accounts: PullFeedInstructionAccountMetas,
        pub data: PullFeedInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PullFeed instruction
    #[derive(Debug, Clone, Default)]
    pub struct PullFeedInstructionAccountMetas {
        pub feed: AccountMeta,
    }

    /// Account pubkeys for PullFeed instruction
    #[derive(Debug, Clone)]
    pub struct PullFeedInstructionAccounts {
        pub feed: Pubkey,
    }

    impl PullFeedInstructionAccounts {
        pub fn new(feed: Pubkey) -> Self {
            Self { feed }
        }
    }

    /// Instruction data for PullFeed
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PullFeedInstructionData {}

    impl PullFeedInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PullFeedInstruction
    impl PullFeedInstruction {
        fn discriminator() -> [u8; 8] {
            [80u8, 66u8, 169u8, 113u8, 140u8, 246u8, 129u8, 88u8]
        }

        pub fn data(data: PullFeedInstructionData) -> Self {
            Self {
                accounts: PullFeedInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PullFeedInstructionAccounts) -> Self {
            self.accounts.feed = AccountMeta::new_readonly(accounts.feed, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.feed.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Swap
    // ....................................................................

    /// Main instruction struct for Swap
    pub struct SwapInstruction {
        pub accounts: SwapInstructionAccountMetas,
        pub data: SwapInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Swap instruction
    #[derive(Debug, Clone, Default)]
    pub struct SwapInstructionAccountMetas {
        pub amm: AccountMeta,

        pub pool_authority: AccountMeta,

        pub trader: AccountMeta,

        pub mint_a: AccountMeta,

        pub mint_b: AccountMeta,

        pub pool: AccountMeta,

        pub pool_account_a: AccountMeta,

        pub pool_account_b: AccountMeta,

        pub sst: AccountMeta,

        pub trader_account_a: AccountMeta,

        pub trader_account_b: AccountMeta,

        pub payer: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Swap instruction
    #[derive(Debug, Clone)]
    pub struct SwapInstructionAccounts {
        pub amm: Pubkey,

        pub pool_authority: Pubkey,

        pub trader: Pubkey,

        pub mint_a: Pubkey,

        pub mint_b: Pubkey,

        pub pool: Pubkey,

        pub pool_account_a: Pubkey,

        pub pool_account_b: Pubkey,

        pub sst: Pubkey,

        pub trader_account_a: Pubkey,

        pub trader_account_b: Pubkey,

        pub payer: Pubkey,
    }

    impl SwapInstructionAccounts {
        pub fn new(
            amm: Pubkey,

            pool_authority: Pubkey,

            trader: Pubkey,

            mint_a: Pubkey,

            mint_b: Pubkey,

            pool: Pubkey,

            pool_account_a: Pubkey,

            pool_account_b: Pubkey,

            sst: Pubkey,

            trader_account_a: Pubkey,

            trader_account_b: Pubkey,

            payer: Pubkey,
        ) -> Self {
            Self {
                amm,

                pool_authority,

                trader,

                mint_a,

                mint_b,

                pool,

                pool_account_a,

                pool_account_b,

                sst,

                trader_account_a,

                trader_account_b,

                payer,
            }
        }
    }

    /// Instruction data for Swap
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SwapInstructionData {
        pub swap_a: bool,

        pub input_amount: u64,

        pub min_output_amount: u64,
    }

    impl SwapInstructionData {
        pub fn new(swap_a: bool, input_amount: u64, min_output_amount: u64) -> Self {
            Self {
                swap_a,

                input_amount,

                min_output_amount,
            }
        }
    }

    /// Implementation for SwapInstruction
    impl SwapInstruction {
        fn discriminator() -> [u8; 8] {
            [248u8, 198u8, 158u8, 145u8, 225u8, 117u8, 135u8, 200u8]
        }

        pub fn data(data: SwapInstructionData) -> Self {
            Self {
                accounts: SwapInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SwapInstructionAccounts) -> Self {
            self.accounts.amm = AccountMeta::new_readonly(accounts.amm, false);

            self.accounts.pool_authority = AccountMeta::new(accounts.pool_authority, false);

            self.accounts.trader = AccountMeta::new_readonly(accounts.trader, true);

            self.accounts.mint_a = AccountMeta::new_readonly(accounts.mint_a, false);

            self.accounts.mint_b = AccountMeta::new_readonly(accounts.mint_b, false);

            self.accounts.pool = AccountMeta::new_readonly(accounts.pool, false);

            self.accounts.pool_account_a = AccountMeta::new(accounts.pool_account_a, false);

            self.accounts.pool_account_b = AccountMeta::new(accounts.pool_account_b, false);

            self.accounts.sst = AccountMeta::new_readonly(accounts.sst, false);

            self.accounts.trader_account_a = AccountMeta::new(accounts.trader_account_a, false);

            self.accounts.trader_account_b = AccountMeta::new(accounts.trader_account_b, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.token_program = AccountMeta::new_readonly(
                pubkey!("TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"),
                false,
            );

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.pool_authority.clone());

            metas.push(self.accounts.trader.clone());

            metas.push(self.accounts.mint_a.clone());

            metas.push(self.accounts.mint_b.clone());

            metas.push(self.accounts.pool.clone());

            metas.push(self.accounts.pool_account_a.clone());

            metas.push(self.accounts.pool_account_b.clone());

            metas.push(self.accounts.sst.clone());

            metas.push(self.accounts.trader_account_a.clone());

            metas.push(self.accounts.trader_account_b.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateAdmin
    // ....................................................................

    /// Main instruction struct for UpdateAdmin
    pub struct UpdateAdminInstruction {
        pub accounts: UpdateAdminInstructionAccountMetas,
        pub data: UpdateAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateAdminInstructionAccountMetas {
        pub amm: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for UpdateAdmin instruction
    #[derive(Debug, Clone)]
    pub struct UpdateAdminInstructionAccounts {
        pub amm: Pubkey,

        pub admin: Pubkey,
    }

    impl UpdateAdminInstructionAccounts {
        pub fn new(amm: Pubkey, admin: Pubkey) -> Self {
            Self { amm, admin }
        }
    }

    /// Instruction data for UpdateAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateAdminInstructionData {
        pub new_admin: Pubkey,
    }

    impl UpdateAdminInstructionData {
        pub fn new(new_admin: Pubkey) -> Self {
            Self { new_admin }
        }
    }

    /// Implementation for UpdateAdminInstruction
    impl UpdateAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [161u8, 176u8, 40u8, 213u8, 60u8, 184u8, 179u8, 228u8]
        }

        pub fn data(data: UpdateAdminInstructionData) -> Self {
            Self {
                accounts: UpdateAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateAdminInstructionAccounts) -> Self {
            self.accounts.amm = AccountMeta::new(accounts.amm, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateFee
    // ....................................................................

    /// Main instruction struct for UpdateFee
    pub struct UpdateFeeInstruction {
        pub accounts: UpdateFeeInstructionAccountMetas,
        pub data: UpdateFeeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateFee instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateFeeInstructionAccountMetas {
        pub amm: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for UpdateFee instruction
    #[derive(Debug, Clone)]
    pub struct UpdateFeeInstructionAccounts {
        pub amm: Pubkey,

        pub admin: Pubkey,
    }

    impl UpdateFeeInstructionAccounts {
        pub fn new(amm: Pubkey, admin: Pubkey) -> Self {
            Self { amm, admin }
        }
    }

    /// Instruction data for UpdateFee
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateFeeInstructionData {
        pub new_fee: u16,
    }

    impl UpdateFeeInstructionData {
        pub fn new(new_fee: u16) -> Self {
            Self { new_fee }
        }
    }

    /// Implementation for UpdateFeeInstruction
    impl UpdateFeeInstruction {
        fn discriminator() -> [u8; 8] {
            [232u8, 253u8, 195u8, 247u8, 148u8, 212u8, 73u8, 222u8]
        }

        pub fn data(data: UpdateFeeInstructionData) -> Self {
            Self {
                accounts: UpdateFeeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateFeeInstructionAccounts) -> Self {
            self.accounts.amm = AccountMeta::new(accounts.amm, false);

            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.amm.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateTimestamp
    // ....................................................................

    /// Main instruction struct for UpdateTimestamp
    pub struct UpdateTimestampInstruction {
        pub accounts: UpdateTimestampInstructionAccountMetas,
        pub data: UpdateTimestampInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateTimestamp instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateTimestampInstructionAccountMetas {
        pub time: AccountMeta,

        pub payer: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdateTimestamp instruction
    #[derive(Debug, Clone)]
    pub struct UpdateTimestampInstructionAccounts {
        pub time: Pubkey,

        pub payer: Pubkey,
    }

    impl UpdateTimestampInstructionAccounts {
        pub fn new(time: Pubkey, payer: Pubkey) -> Self {
            Self { time, payer }
        }
    }

    /// Instruction data for UpdateTimestamp
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateTimestampInstructionData {}

    impl UpdateTimestampInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UpdateTimestampInstruction
    impl UpdateTimestampInstruction {
        fn discriminator() -> [u8; 8] {
            [80u8, 68u8, 198u8, 75u8, 117u8, 231u8, 159u8, 218u8]
        }

        pub fn data(data: UpdateTimestampInstructionData) -> Self {
            Self {
                accounts: UpdateTimestampInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateTimestampInstructionAccounts) -> Self {
            self.accounts.time = AccountMeta::new(accounts.time, false);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.time.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: Amm
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Amm {
    pub admin: Pubkey,

    pub fee: u16,

    pub created: bool,
}

impl Amm {
    pub fn new(admin: Pubkey, fee: u16, created: bool) -> Self {
        Self {
            admin,

            fee,

            created,
        }
    }
}

/// Custom struct: Pool
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Pool {
    pub amm: Pubkey,

    pub mint_a: Pubkey,

    pub mint_b: Pubkey,
}

impl Pool {
    pub fn new(amm: Pubkey, mint_a: Pubkey, mint_b: Pubkey) -> Self {
        Self {
            amm,

            mint_a,

            mint_b,
        }
    }
}

/// Custom struct: RewardVault
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RewardVault {
    pub pool: Pubkey,

    pub mint_a: Pubkey,

    pub mint_b: Pubkey,

    pub bump: u8,
}

impl RewardVault {
    pub fn new(pool: Pubkey, mint_a: Pubkey, mint_b: Pubkey, bump: u8) -> Self {
        Self {
            pool,

            mint_a,

            mint_b,

            bump,
        }
    }
}

/// Custom struct: SST
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct SST {
    pub temperature: f64,

    pub created: bool,
}

impl SST {
    pub fn new(temperature: f64, created: bool) -> Self {
        Self {
            temperature,

            created,
        }
    }
}

/// Custom struct: Time
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct Time {
    pub created: bool,

    pub timestamp: i64,
}

impl Time {
    pub fn new(created: bool, timestamp: i64) -> Self {
        Self { created, timestamp }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
